# Generated by Django 3.0.3 on 2021-05-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=0)),
                ('Image', models.ImageField(upload_to='activity/')),
            ],
        ),
        migrations.CreateModel(
            name='collaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(default='iist', max_length=30)),
                ('Image', models.ImageField(upload_to='collaboration/')),
            ],
        ),
        migrations.CreateModel(
            name='crousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=0)),
                ('Image', models.ImageField(upload_to='crousel/')),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=0)),
                ('Image', models.ImageField(upload_to='story/')),
            ],
        ),
    ]
