# Generated by Django 3.0.3 on 2021-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='crousel',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='story',
            name='Number',
        ),
        migrations.AddField(
            model_name='activity',
            name='Tag',
            field=models.CharField(default='iist', max_length=30),
        ),
        migrations.AddField(
            model_name='crousel',
            name='Tag',
            field=models.CharField(default='iist', max_length=30),
        ),
        migrations.AddField(
            model_name='story',
            name='Tag',
            field=models.CharField(default='iist', max_length=30),
        ),
    ]
