# Generated by Django 3.0.3 on 2021-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_collaboration_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='order',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='activity',
            name='Order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crousel',
            name='Order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='Order',
            field=models.IntegerField(default=0),
        ),
    ]
