# Generated by Django 3.0.3 on 2021-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210508_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='Detail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
