# Generated by Django 3.0.3 on 2021-05-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_collaboration_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='Detail',
        ),
    ]
