# Generated by Django 3.0.3 on 2021-05-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_dg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DG',
        ),
    ]
