# Generated by Django 3.0.3 on 2021-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_delete_dg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='dg/')),
            ],
        ),
    ]
